Repository rancher/k3os, pull requests merged in 2019-11, with the labels that each got.

#249 ccapply: avoid aggressive fail when reading ssh keys from github
  overlay/etc/conf.d/net-online
  pkg/ssh/ssh.go
  scripts/run-qemu
Labels: area/configuration, area/networking

#258 Adding packer templates for vSphere
  package/packer/vsphere/README.md
  package/packer/vsphere/agent/k3os-agent-variables.json
  package/packer/vsphere/agent/k3os-agent.json
  package/packer/vsphere/server/k3os-server-variables.json
  package/packer/vsphere/server/k3os-server.json
Labels: area/virtualization

#273 install: bump initially partitioned disk from 500MB to 700MB
  install.sh
Labels: area/installation

#275 ccapply: add label with the value of k3os.mode
  pkg/cc/funcs.go
Labels: area/configuration

#283 k3s: v1.0.0-rc5
  go.sum
  images/01-k3s/Dockerfile
Labels: area/k3s

#292 tooling: toolbox, rng-tools, htop, qemu-guest-agent
  images/00-base/Dockerfile
  overlay/libexec/k3os/boot
  overlay/sbin/toolbox
Labels: area/tooling
