Repository rancher/k3os, pull requests merged in 2019-09, with the labels that each got.

#191 boot: with wifi config, have connman "want" wpa_supplicant
  overlay/etc/conf.d/wpa_supplicant
  overlay/etc/wpa_supplicant/wpa_supplicant.conf
  overlay/libexec/k3os/boot
Labels: area/networking

#192 pre-init: fix growpart logic to handle nvme partitions
  overlay/libexec/k3os/boot
  overlay/libexec/k3os/mode-disk
Labels: area/installation, kind/bug

#182 GCP Packer build
  package/packer/gcp/gcp.yaml
  package/packer/gcp/template.json
Labels: area/cloud
