Repository rancher/k3os, pull requests merged in 2020-01, with the labels that each got.

#228 Reboot on takeover install
  install.sh
  overlay/libexec/k3os/mode-disk
  package/packer/aws/template-arm64.json
  package/packer/aws/template.json
Labels: area/installation

#143 Fix #82: honor k3os.install.power_off when k3os.mode=install.
  install.sh
Labels: area/installation

#348 cli: upgrade sub-command
  go.mod
  go.sum
  pkg/cli/app/app.go
  pkg/cli/install/install.go
  pkg/cli/upgrade/upgrade.go
  pkg/system/component.go
  vendor/github.com/otiai10/copy/.gitignore
  vendor/github.com/otiai10/copy/.travis.yml
  vendor/github.com/otiai10/copy/LICENSE
  vendor/github.com/otiai10/copy/README.md
  vendor/github.com/otiai10/copy/copy.go
  vendor/github.com/otiai10/copy/go.mod
  vendor/github.com/otiai10/copy/go.sum
  vendor/modules.txt
Labels: area/upgrade, kind/feature

#352 Add support for tftp:// and ftp:// config_url and iso_url.
  install.sh
Labels: area/installation

#355 update linuxkit/metadata supporting hetzner
  README.md
  images/02-progs/Dockerfile
Labels: area/cloud

#360 storage tooling: add iscsi, lvm2, and multipath-tools
  images/00-base/Dockerfile
Labels: area/storage, area/tooling

#364 readme: note grub2 differences on non-alpine platforms
  README.md
Labels: area/documentation

#369 deprecate upgrade scripts in favor of upgrade controller
  overlay/share/rancher/k3os/scripts/k3os-upgrade-kernel
  overlay/share/rancher/k3os/scripts/k3os-upgrade-rootfs
  overlay/share/rancher/k3os/scripts/toolbox
  overlay/share/rancher/k3s/server/manifests/system-upgrade-controller.yaml
  overlay/share/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml
  scripts/package
  scripts/version
Labels: area/tooling, area/upgrade
